title: OSR & Nico
description: Règles et autres pour jouer à OSR avec Nico
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: "https://drloser123.github.io/"

aux_links:
  Règles d'Old-School Essentials: 
    - https://oldschoolessentials.necroticgnome.com/fr/srd/index.php/Main_Page
